# Generated by Django 4.0.2 on 2022-02-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Incomplete', 'Incomplete ❌'), ('Completed', 'Completeed ✔️'), ('Overdue', 'Overdue ⌛')], max_length=200, null=True)),
                ('due_date', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
