# Generated by Django 4.0.2 on 2022-02-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete ❌'), ('Completed', 'Completed ✔️'), ('Overdue', 'Overdue ⌛')], max_length=200, null=True),
        ),
    ]
