# Generated by Django 4.0.2 on 2022-02-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
